# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build project
        run: cd formkiq && npm install

      - name: Build project
        run: cd formkiq && npx nx build formkiq-document-console-react

      - name: Zip project
        run: cd formkiq/dist/apps/formkiq-document-console-react && zip -r formkiq-console.zip *

      - uses: nyaa8/package-version@v1
        with:
          path: "formkiq/package.json"
          follow-symlinks: "false" # Optional
